# Generated by Django 5.2.1 on 2025-06-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultlytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.CharField(max_length=20)),
                ('consulting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='consultlytics.consulting')),
            ],
            options={
                'db_table': 'consulting_detail',
                'ordering': ['timestamp'],
            },
        ),
    ]
