import os
import django
import json
import random
from datetime import datetime, timedelta

# Django 환경 설정
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from apps.consultlytics.models import Consulting, ConsultingDetail

# 샘플 카테고리/텍스트/키워드
mid_categories = ["상품문의", "해지", "대출", "이자", "펀드", "수수료", "보험", "환불", "카드", "비밀번호"]
content_categories = ["정기예금", "적금", "신용대출", "주택담보대출", "펀드가입", "수수료문의", "보험가입", "환불요청", "카드발급", "비밀번호변경"]
sentiments = ["positive", "neutral", "negative"]
sent_labels = ["만족", "불만족", "보통"]
speakers = ["CSR", "고객"]


def create_sample_data():
    # 기존 데이터 삭제
    ConsultingDetail.objects.all().delete()
    Consulting.objects.all().delete()
    
    # 샘플 데이터 생성
    sample_data = [
        {
            "call_id": "CALL_001",
            "call_date": datetime(2024, 6, 1, 10, 0),
            "call_duration": 300,
            "silence": 40,
            "csr_speech_count": 40,
            "customer_speech_count": 35,
            "csr_emotion_score": 4.5,
            "customer_emotion_score": 4.0,
            "efficiency_score": 90,
            "final_score": 92,
            "alternative_solution_count": 2,
            "apology_ratio": 0.1,
            "positive_word_ratio": 0.8,
            "euphonious_word_ratio": 0.85,
            "empathy_expression_ratio": 0.9,
            "emo_1_star_score": False,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": True,
            "emo_5_star_score": True,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": True,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": False,
            "strength": "친절한 응대",
            "weakness": "설명 부족",
            "improvement": "추가 설명 필요",
            "manual_compliance_ratio": 0.95,
            "score": 91,
            "consulting_content": "고객: 예금 상품 문의\nCSR: 상품 안내 및 설명",
            "Extension": "wav",
            "Path": "/sample/path/audio_1.wav",
            "Rate": 16000,
            "Channels": 1,
            "Duration": 4800000,
            "MinFreq": 50,
            "MaxFreq": 5000,
            "RMSLoudness": 0.8,
            "ZeroCrossingRate": 0.05,
            "SpectralCentroid": 2000,
            "SpectralBandwidth": 1500,
            "SpectralFlatness": 0.3,
            "RollOff": 4000,
            "Chroma_stft": json.dumps([0.5]*12),
            "SpectralContrast": json.dumps([0.4]*7),
            "Tonnetz": json.dumps([0.1]*6),
            "MFCC_0_13": json.dumps([0.2]*14),
            "Summary": "예금 상품 안내 상담",
            "Conflict": False,
            "Speaker": "CSR",
            "Sequence": 1,
            "StartTime": 0,
            "EndTime": 5000,
            "Content": "예금 상품에 대한 설명",
            "Sentiment": "positive",
            "Profane": False,
            "top_nouns": json.dumps(["예금", "상품", "이자", "고객", "안내", "설명", "문의", "상담", "금리", "조건"]),
            "sent_score": 0.9,
            "sent_label": "만족",
            "mid_category": "상품문의",
            "content_category": "정기예금",
            "script_phrase_ratio": 0.8,
            "honorific_ratio": 0.9,
            "confirmation_ratio": 0.7,
            "request_ratio": 0.5,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_002",
            "call_date": datetime(2024, 6, 2, 11, 30),
            "call_duration": 420,
            "silence": 60,
            "csr_speech_count": 38,
            "customer_speech_count": 40,
            "csr_emotion_score": 3.8,
            "customer_emotion_score": 3.5,
            "efficiency_score": 85,
            "final_score": 80,
            "alternative_solution_count": 1,
            "apology_ratio": 0.2,
            "positive_word_ratio": 0.7,
            "euphonious_word_ratio": 0.7,
            "empathy_expression_ratio": 0.8,
            "emo_1_star_score": False,
            "emo_2_star_score": True,
            "emo_3_star_score": True,
            "emo_4_star_score": False,
            "emo_5_star_score": False,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": True,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": False,
            "strength": "빠른 처리",
            "weakness": "공감 부족",
            "improvement": "공감 표현 강화",
            "manual_compliance_ratio": 0.85,
            "score": 78,
            "consulting_content": "고객: 대출 문의\nCSR: 대출 조건 안내",
            "Extension": "mp3",
            "Path": "/sample/path/audio_2.mp3",
            "Rate": 22050,
            "Channels": 2,
            "Duration": 9240000,
            "MinFreq": 60,
            "MaxFreq": 6000,
            "RMSLoudness": 0.7,
            "ZeroCrossingRate": 0.07,
            "SpectralCentroid": 2500,
            "SpectralBandwidth": 1800,
            "SpectralFlatness": 0.4,
            "RollOff": 5000,
            "Chroma_stft": json.dumps([0.6]*12),
            "SpectralContrast": json.dumps([0.5]*7),
            "Tonnetz": json.dumps([0.2]*6),
            "MFCC_0_13": json.dumps([0.3]*14),
            "Summary": "대출 조건 안내 상담",
            "Conflict": False,
            "Speaker": "고객",
            "Sequence": 2,
            "StartTime": 1000,
            "EndTime": 7000,
            "Content": "대출 조건에 대한 문의",
            "Sentiment": "neutral",
            "Profane": False,
            "top_nouns": json.dumps(["대출", "조건", "고객", "안내", "상담", "이자", "한도", "신청", "승인", "기간"]),
            "sent_score": 0.6,
            "sent_label": "보통",
            "mid_category": "대출",
            "content_category": "신용대출",
            "script_phrase_ratio": 0.7,
            "honorific_ratio": 0.8,
            "confirmation_ratio": 0.6,
            "request_ratio": 0.4,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_003",
            "call_date": datetime(2024, 6, 3, 9, 15),
            "call_duration": 600,
            "silence": 80,
            "csr_speech_count": 50,
            "customer_speech_count": 45,
            "csr_emotion_score": 2.9,
            "customer_emotion_score": 2.5,
            "efficiency_score": 70,
            "final_score": 68,
            "alternative_solution_count": 0,
            "apology_ratio": 0.3,
            "positive_word_ratio": 0.6,
            "euphonious_word_ratio": 0.6,
            "empathy_expression_ratio": 0.7,
            "emo_1_star_score": True,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": False,
            "emo_5_star_score": False,
            "고객_emo_1_star_score": True,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": False,
            "고객_emo_5_star_score": False,
            "strength": "정확한 정보 제공",
            "weakness": "친절 부족",
            "improvement": "친절한 응대 필요",
            "manual_compliance_ratio": 0.75,
            "score": 65,
            "consulting_content": "고객: 해지 문의\nCSR: 해지 절차 안내",
            "Extension": "flac",
            "Path": "/sample/path/audio_3.flac",
            "Rate": 44100,
            "Channels": 2,
            "Duration": 26460000,
            "MinFreq": 40,
            "MaxFreq": 7000,
            "RMSLoudness": 0.6,
            "ZeroCrossingRate": 0.09,
            "SpectralCentroid": 3000,
            "SpectralBandwidth": 2000,
            "SpectralFlatness": 0.5,
            "RollOff": 6000,
            "Chroma_stft": json.dumps([0.7]*12),
            "SpectralContrast": json.dumps([0.6]*7),
            "Tonnetz": json.dumps([0.3]*6),
            "MFCC_0_13": json.dumps([0.4]*14),
            "Summary": "해지 절차 안내 상담",
            "Conflict": True,
            "Speaker": "CSR",
            "Sequence": 3,
            "StartTime": 2000,
            "EndTime": 9000,
            "Content": "해지 절차에 대한 설명",
            "Sentiment": "negative",
            "Profane": False,
            "top_nouns": json.dumps(["해지", "절차", "고객", "상담", "안내", "계좌", "이체", "수수료", "문의", "설명"]),
            "sent_score": 0.3,
            "sent_label": "불만족",
            "mid_category": "해지",
            "content_category": "적금",
            "script_phrase_ratio": 0.6,
            "honorific_ratio": 0.7,
            "confirmation_ratio": 0.5,
            "request_ratio": 0.3,
            "conflict_flag": True
        },
        {
            "call_id": "CALL_004",
            "call_date": datetime(2024, 6, 4, 14, 0),
            "call_duration": 240,
            "silence": 30,
            "csr_speech_count": 35,
            "customer_speech_count": 30,
            "csr_emotion_score": 4.2,
            "customer_emotion_score": 4.7,
            "efficiency_score": 95,
            "final_score": 97,
            "alternative_solution_count": 3,
            "apology_ratio": 0.05,
            "positive_word_ratio": 0.9,
            "euphonious_word_ratio": 0.92,
            "empathy_expression_ratio": 0.95,
            "emo_1_star_score": False,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": False,
            "emo_5_star_score": True,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": True,
            "strength": "공감 능력 우수",
            "weakness": "없음",
            "improvement": "지속 유지 필요",
            "manual_compliance_ratio": 0.99,
            "score": 98,
            "consulting_content": "고객: 펀드 가입 문의\nCSR: 펀드 상품 안내",
            "Extension": "wav",
            "Path": "/sample/path/audio_4.wav",
            "Rate": 16000,
            "Channels": 1,
            "Duration": 3840000,
            "MinFreq": 55,
            "MaxFreq": 4800,
            "RMSLoudness": 0.9,
            "ZeroCrossingRate": 0.04,
            "SpectralCentroid": 1800,
            "SpectralBandwidth": 1400,
            "SpectralFlatness": 0.2,
            "RollOff": 3500,
            "Chroma_stft": json.dumps([0.4]*12),
            "SpectralContrast": json.dumps([0.3]*7),
            "Tonnetz": json.dumps([0.0]*6),
            "MFCC_0_13": json.dumps([0.1]*14),
            "Summary": "펀드 상품 안내 상담",
            "Conflict": False,
            "Speaker": "고객",
            "Sequence": 4,
            "StartTime": 500,
            "EndTime": 4000,
            "Content": "펀드 상품에 대한 문의",
            "Sentiment": "positive",
            "Profane": False,
            "top_nouns": json.dumps(["펀드", "상품", "고객", "가입", "안내", "상담", "수익", "설명", "문의", "조건"]),
            "sent_score": 0.95,
            "sent_label": "만족",
            "mid_category": "펀드",
            "content_category": "펀드가입",
            "script_phrase_ratio": 0.9,
            "honorific_ratio": 1.0,
            "confirmation_ratio": 0.8,
            "request_ratio": 0.6,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_005",
            "call_date": datetime(2024, 6, 5, 16, 45),
            "call_duration": 360,
            "silence": 50,
            "csr_speech_count": 42,
            "customer_speech_count": 38,
            "csr_emotion_score": 3.5,
            "customer_emotion_score": 3.2,
            "efficiency_score": 80,
            "final_score": 82,
            "alternative_solution_count": 1,
            "apology_ratio": 0.15,
            "positive_word_ratio": 0.75,
            "euphonious_word_ratio": 0.8,
            "empathy_expression_ratio": 0.85,
            "emo_1_star_score": False,
            "emo_2_star_score": True,
            "emo_3_star_score": False,
            "emo_4_star_score": True,
            "emo_5_star_score": False,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": True,
            "고객_emo_3_star_score": True,
            "고객_emo_4_star_score": False,
            "고객_emo_5_star_score": False,
            "strength": "명확한 안내",
            "weakness": "공감 부족",
            "improvement": "공감 표현 필요",
            "manual_compliance_ratio": 0.88,
            "score": 80,
            "consulting_content": "고객: 카드 발급 문의\nCSR: 카드 발급 절차 안내",
            "Extension": "mp3",
            "Path": "/sample/path/audio_5.mp3",
            "Rate": 22050,
            "Channels": 2,
            "Duration": 7938000,
            "MinFreq": 65,
            "MaxFreq": 5200,
            "RMSLoudness": 0.75,
            "ZeroCrossingRate": 0.06,
            "SpectralCentroid": 2200,
            "SpectralBandwidth": 1600,
            "SpectralFlatness": 0.35,
            "RollOff": 4200,
            "Chroma_stft": json.dumps([0.55]*12),
            "SpectralContrast": json.dumps([0.45]*7),
            "Tonnetz": json.dumps([0.15]*6),
            "MFCC_0_13": json.dumps([0.25]*14),
            "Summary": "카드 발급 안내 상담",
            "Conflict": False,
            "Speaker": "CSR",
            "Sequence": 5,
            "StartTime": 1500,
            "EndTime": 8000,
            "Content": "카드 발급 절차에 대한 설명",
            "Sentiment": "neutral",
            "Profane": False,
            "top_nouns": json.dumps(["카드", "발급", "고객", "안내", "상담", "절차", "문의", "설명", "조건", "수수료"]),
            "sent_score": 0.7,
            "sent_label": "보통",
            "mid_category": "카드",
            "content_category": "카드발급",
            "script_phrase_ratio": 0.75,
            "honorific_ratio": 0.85,
            "confirmation_ratio": 0.65,
            "request_ratio": 0.55,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_006",
            "call_date": datetime(2024, 6, 6, 16, 0),
            "call_duration": 660,
            "silence": 35,
            "csr_speech_count": 25,
            "customer_speech_count": 22,
            "csr_emotion_score": 88,
            "customer_emotion_score": 82,
            "efficiency_score": 94,
            "final_score": 92,
            "alternative_solution_count": 3,
            "apology_ratio": 0.08,
            "positive_word_ratio": 0.88,
            "euphonious_word_ratio": 0.92,
            "empathy_expression_ratio": 0.95,
            "emo_1_star_score": False,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": False,
            "emo_5_star_score": True,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": True,
            "strength": "공감 능력 우수",
            "weakness": "없음",
            "improvement": "지속 유지 필요",
            "manual_compliance_ratio": 0.98,
            "score": 96,
            "consulting_content": "고객: 투자상품 포트폴리오 구성 문의\nCSR: 포트폴리오 구성 조언",
            "Extension": "wav",
            "Path": "/sample/path/audio_6.wav",
            "Rate": 16000,
            "Channels": 1,
            "Duration": 6600000,
            "MinFreq": 50,
            "MaxFreq": 5000,
            "RMSLoudness": 0.9,
            "ZeroCrossingRate": 0.04,
            "SpectralCentroid": 2200,
            "SpectralBandwidth": 2700,
            "SpectralFlatness": 0.2,
            "RollOff": 3700,
            "Chroma_stft": json.dumps([0.4]*12),
            "SpectralContrast": json.dumps([0.3]*7),
            "Tonnetz": json.dumps([0.0]*6),
            "MFCC_0_13": json.dumps([0.1]*14),
            "Summary": "포트폴리오 구성 조언 상담",
            "Conflict": False,
            "Speaker": "고객",
            "Sequence": 6,
            "StartTime": 0,
            "EndTime": 5000,
            "Content": "포트폴리오 구성에 대한 문의",
            "Sentiment": "positive",
            "Profane": False,
            "top_nouns": json.dumps(["포트폴리오", "구성", "고객", "조언", "상담", "수익률", "위험관리", "자산배분"]),
            "sent_score": 0.95,
            "sent_label": "만족",
            "mid_category": "투자",
            "content_category": "포트폴리오구성",
            "script_phrase_ratio": 0.88,
            "honorific_ratio": 0.95,
            "confirmation_ratio": 0.85,
            "request_ratio": 0.65,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_007",
            "call_date": datetime(2024, 6, 7, 16, 45),
            "call_duration": 720,
            "silence": 50,
            "csr_speech_count": 28,
            "customer_speech_count": 25,
            "csr_emotion_score": 72,
            "customer_emotion_score": 68,
            "efficiency_score": 82,
            "final_score": 79,
            "alternative_solution_count": 1,
            "apology_ratio": 0.15,
            "positive_word_ratio": 0.75,
            "euphonious_word_ratio": 0.78,
            "empathy_expression_ratio": 0.78,
            "emo_1_star_score": False,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": False,
            "emo_5_star_score": False,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": False,
            "고객_emo_5_star_score": False,
            "strength": "정확한 정보 제공",
            "weakness": "친절 부족",
            "improvement": "친절한 응대 필요",
            "manual_compliance_ratio": 0.85,
            "score": 79,
            "consulting_content": "고객: 대출 상품 변경 절차 문의\nCSR: 대출 변경 절차 설명",
            "Extension": "mp3",
            "Path": "/sample/path/audio_7.mp3",
            "Rate": 22050,
            "Channels": 2,
            "Duration": 7200000,
            "MinFreq": 60,
            "MaxFreq": 5200,
            "RMSLoudness": 0.75,
            "ZeroCrossingRate": 0.16,
            "SpectralCentroid": 2600,
            "SpectralBandwidth": 3100,
            "SpectralFlatness": 0.32,
            "RollOff": 4100,
            "Chroma_stft": json.dumps([0.55]*12),
            "SpectralContrast": json.dumps([0.45]*7),
            "Tonnetz": json.dumps([0.15]*6),
            "MFCC_0_13": json.dumps([0.25]*14),
            "Summary": "대출 변경 절차 설명 상담",
            "Conflict": False,
            "Speaker": "CSR",
            "Sequence": 7,
            "StartTime": 0,
            "EndTime": 5000,
            "Content": "대출 변경 절차에 대한 설명",
            "Sentiment": "neutral",
            "Profane": False,
            "top_nouns": json.dumps(["대출", "변경", "절차", "고객", "설명", "상담", "이자율", "조건변경", "서류"]),
            "sent_score": 0.75,
            "sent_label": "보통",
            "mid_category": "대출",
            "content_category": "대출변경",
            "script_phrase_ratio": 0.75,
            "honorific_ratio": 0.82,
            "confirmation_ratio": 0.72,
            "request_ratio": 0.58,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_008",
            "call_date": datetime(2024, 6, 8, 13, 20),
            "call_duration": 480,
            "silence": 45,
            "csr_speech_count": 30,
            "customer_speech_count": 28,
            "csr_emotion_score": 4.0,
            "customer_emotion_score": 3.7,
            "efficiency_score": 88,
            "final_score": 85,
            "alternative_solution_count": 2,
            "apology_ratio": 0.12,
            "positive_word_ratio": 0.82,
            "euphonious_word_ratio": 0.8,
            "empathy_expression_ratio": 0.87,
            "emo_1_star_score": False,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": True,
            "emo_5_star_score": False,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": True,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": False,
            "strength": "신속한 문제 해결",
            "weakness": "추가 설명 부족",
            "improvement": "상세한 안내 필요",
            "manual_compliance_ratio": 0.9,
            "score": 84,
            "consulting_content": "고객: 보험 해지 문의\nCSR: 해지 절차 및 필요 서류 안내",
            "Extension": "wav",
            "Path": "/sample/path/audio_8.wav",
            "Rate": 16000,
            "Channels": 1,
            "Duration": 4800000,
            "MinFreq": 55,
            "MaxFreq": 4800,
            "RMSLoudness": 0.78,
            "ZeroCrossingRate": 0.08,
            "SpectralCentroid": 2100,
            "SpectralBandwidth": 1700,
            "SpectralFlatness": 0.28,
            "RollOff": 3900,
            "Chroma_stft": json.dumps([0.52]*12),
            "SpectralContrast": json.dumps([0.42]*7),
            "Tonnetz": json.dumps([0.12]*6),
            "MFCC_0_13": json.dumps([0.22]*14),
            "Summary": "보험 해지 절차 안내 상담",
            "Conflict": False,
            "Speaker": "CSR",
            "Sequence": 8,
            "StartTime": 0,
            "EndTime": 5000,
            "Content": "보험 해지 절차에 대한 설명",
            "Sentiment": "neutral",
            "Profane": False,
            "top_nouns": json.dumps(["보험", "해지", "고객", "서류", "절차", "상담", "안내", "문의", "계약"]),
            "sent_score": 0.68,
            "sent_label": "보통",
            "mid_category": "보험",
            "content_category": "보험가입",
            "script_phrase_ratio": 0.78,
            "honorific_ratio": 0.88,
            "confirmation_ratio": 0.68,
            "request_ratio": 0.48,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_009",
            "call_date": datetime(2024, 6, 9, 15, 10),
            "call_duration": 540,
            "silence": 55,
            "csr_speech_count": 33,
            "customer_speech_count": 31,
            "csr_emotion_score": 3.6,
            "customer_emotion_score": 3.9,
            "efficiency_score": 83,
            "final_score": 81,
            "alternative_solution_count": 1,
            "apology_ratio": 0.18,
            "positive_word_ratio": 0.7,
            "euphonious_word_ratio": 0.75,
            "empathy_expression_ratio": 0.8,
            "emo_1_star_score": False,
            "emo_2_star_score": True,
            "emo_3_star_score": False,
            "emo_4_star_score": True,
            "emo_5_star_score": False,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": True,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": False,
            "strength": "정확한 절차 안내",
            "weakness": "공감 부족",
            "improvement": "공감 표현 강화",
            "manual_compliance_ratio": 0.86,
            "score": 80,
            "consulting_content": "고객: 환불 요청\nCSR: 환불 절차 및 소요 시간 안내",
            "Extension": "mp3",
            "Path": "/sample/path/audio_9.mp3",
            "Rate": 22050,
            "Channels": 2,
            "Duration": 8100000,
            "MinFreq": 60,
            "MaxFreq": 5100,
            "RMSLoudness": 0.7,
            "ZeroCrossingRate": 0.09,
            "SpectralCentroid": 2300,
            "SpectralBandwidth": 1800,
            "SpectralFlatness": 0.33,
            "RollOff": 4300,
            "Chroma_stft": json.dumps([0.57]*12),
            "SpectralContrast": json.dumps([0.47]*7),
            "Tonnetz": json.dumps([0.17]*6),
            "MFCC_0_13": json.dumps([0.27]*14),
            "Summary": "환불 절차 안내 상담",
            "Conflict": False,
            "Speaker": "고객",
            "Sequence": 9,
            "StartTime": 0,
            "EndTime": 5000,
            "Content": "환불 절차 및 소요 시간에 대한 설명",
            "Sentiment": "neutral",
            "Profane": False,
            "top_nouns": json.dumps(["환불", "절차", "고객", "상담", "안내", "문의", "소요시간", "계좌"]),
            "sent_score": 0.65,
            "sent_label": "보통",
            "mid_category": "환불",
            "content_category": "환불요청",
            "script_phrase_ratio": 0.7,
            "honorific_ratio": 0.8,
            "confirmation_ratio": 0.6,
            "request_ratio": 0.5,
            "conflict_flag": False
        },
        {
            "call_id": "CALL_010",
            "call_date": datetime(2024, 6, 10, 15, 30),
            "call_duration": 360,
            "silence": 45,
            "csr_speech_count": 42,
            "customer_speech_count": 38,
            "csr_emotion_score": 4.3,
            "customer_emotion_score": 4.1,
            "efficiency_score": 88,
            "final_score": 90,
            "alternative_solution_count": 2,
            "apology_ratio": 0.08,
            "positive_word_ratio": 0.85,
            "euphonious_word_ratio": 0.88,
            "empathy_expression_ratio": 0.92,
            "emo_1_star_score": False,
            "emo_2_star_score": False,
            "emo_3_star_score": False,
            "emo_4_star_score": True,
            "emo_5_star_score": True,
            "고객_emo_1_star_score": False,
            "고객_emo_2_star_score": False,
            "고객_emo_3_star_score": False,
            "고객_emo_4_star_score": True,
            "고객_emo_5_star_score": True,
            "strength": "친절한 응대와 정확한 정보 제공",
            "weakness": "처리 시간 다소 지연",
            "improvement": "처리 속도 개선 필요",
            "manual_compliance_ratio": 0.92,
            "score": 89,
            "consulting_content": "고객: 카드 발급 문의\nCSR: 카드 상품 안내 및 발급 절차 설명",
            "Extension": "wav",
            "Path": "/sample/path/audio_10.wav",
            "Rate": 16000,
            "Channels": 1,
            "Duration": 5760000,
            "MinFreq": 50,
            "MaxFreq": 5000,
            "RMSLoudness": 0.75,
            "ZeroCrossingRate": 0.06,
            "SpectralCentroid": 2200,
            "SpectralBandwidth": 1600,
            "SpectralFlatness": 0.35,
            "RollOff": 4500,
            "Chroma_stft": json.dumps([0.55]*12),
            "SpectralContrast": json.dumps([0.45]*7),
            "Tonnetz": json.dumps([0.15]*6),
            "MFCC_0_13": json.dumps([0.25]*14),
            "Summary": "카드 발급 절차 안내 상담",
            "Conflict": False,
            "Speaker": "CSR",
            "Sequence": 10,
            "StartTime": 0,
            "EndTime": 6000,
            "Content": "카드 발급 절차에 대한 설명",
            "Sentiment": "positive",
            "Profane": False,
            "top_nouns": json.dumps(["카드", "발급", "절차", "고객", "안내", "상담", "신청", "서류", "심사", "기간"]),
            "sent_score": 0.85,
            "sent_label": "만족",
            "mid_category": "카드",
            "content_category": "카드발급",
            "script_phrase_ratio": 0.85,
            "honorific_ratio": 0.92,
            "confirmation_ratio": 0.78,
            "request_ratio": 0.45,
            "conflict_flag": False
        }
    ]
    for data in sample_data:
        consulting = Consulting.objects.create(**data)
        print(f"생성된 데이터 ID: {consulting.call_id}")

if __name__ == "__main__":
    create_sample_data() 


    